// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['backend']['UserService']['CreateUser'](arg1, arg2, arg3);
}

export function GetAllUsers() {
  return window['go']['backend']['UserService']['GetAllUsers']();
}

export function GetUserHighestScoreInHistory(arg1) {
  return window['go']['backend']['UserService']['GetUserHighestScoreInHistory'](arg1);
}

export function GetUsersSortedByScore() {
  return window['go']['backend']['UserService']['GetUsersSortedByScore']();
}

export function InsertOrUpdateUser(arg1, arg2, arg3) {
  return window['go']['backend']['UserService']['InsertOrUpdateUser'](arg1, arg2, arg3);
}

export function UpdateUser(arg1, arg2, arg3) {
  return window['go']['backend']['UserService']['UpdateUser'](arg1, arg2, arg3);
}
